version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: udyam-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: udyam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - udyam-network

  # Backend API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: udyam-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:password@postgres:5432/udyam_db?schema=public
      PORT: 5000
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - udyam-network
    volumes:
      - ./backend/src/data:/app/src/data:ro

  # Frontend Next.js App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: udyam-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend:5000
      NEXT_PUBLIC_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - udyam-network

volumes:
  postgres_data:
    driver: local

networks:
  udyam-network:
    driver: bridge
